# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chimpster}
  s.version = "0.1.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Hart, Bob Milani, Phuc Quang"]
  s.date = %q{2011-07-17}
  s.description = %q{Use this gem to send emails through SES via Mailchimp api.}
  s.email = %q{mike@fotomoto.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    ".rake_tasks",
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/chimpster.rb",
    "lib/chimpster/handlers/mail.rb",
    "lib/chimpster/message_extensions/mail.rb",
    "lib/chimpster/message_extensions/shared.rb",
    "chimpster.gemspec",
    "spec/chimpster_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://fotomoto.com}
  s.post_install_message = %q{
      ==================
      Thanks for installing the chimpster gem.
      ==================
    }
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SES Mailchimp API wrapper.}
  s.test_files = [
    "spec/chimpster_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#      s.add_development_dependency(%q<rspec>, [">= 2.6"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_development_dependency(%q<fakeweb-matcher>, [">= 0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<mail>, [">= 0"])
      s.add_development_dependency(%q<uakari>, [">= 0"])
      s.add_dependency(%q<json>, [">= 1.5"])
    else
#      s.add_dependency(%q<rspec>, [">= 2.6"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<fakeweb-matcher>, [">= 0"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 0"])
      s.add_dependency(%q<uakari>, [">= 0"])
      s.add_dependency(%q<json>, [">= 1.5"])
    end
  else
#    s.add_dependency(%q<rspec>, [">= 2.6"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<fakeweb-matcher>, [">= 0"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 0"])
    s.add_dependency(%q<uakari>, [">= 0"])
    s.add_dependency(%q<json>, [">= 1.5"])
  end
end

